### ISSUE TITLE
Files and Nunjucks Templates links

### ISSUE THREAD

**Issue by mertindervish** [adonisjs/docs#120]
Hey! I've just noticed that links for 'Files' and 'Nunjucks Templates' are broken. They both open 'Files' page but content is about templates. I've no problem reading from this repo but it will be nice to be fixed, you know :smile: 

![screenshot](https://cloud.githubusercontent.com/assets/7361642/24265737/2e0e543c-100d-11e7-860c-fce4080dfb6d.png)

**Comment by RomainLanz** [comment]
Hey @mertindervish!

Thanks for reporting this issue! ❤️ 

May you create a PR?

**Comment by mertindervish** [comment]
I've cloned [adonisjs/adonis-documentation](https://github.com/adonisjs/adonis-documentation) repo. When I run `npm run setup` I've got a lot of warnings from asciidoctor:
![screenshot](https://cloud.githubusercontent.com/assets/7361642/24295562/fc2a0d20-10a3-11e7-9b43-fed59775398b.png)

Btw there is no bug in 3.0's documentation. So I guess this is from docketjs's asciidoctor integration?

**Comment by thetutlage** [comment]
Yes these r Warnings from asciidoctor integration

**Comment by mertindervish** [comment]
Are they somehow related to buggy build for Files page? Or is it the normal behaviour?
