### ISSUE TITLE
.body > .overlay CSS issues

### ISSUE THREAD

**Issue by KaelWD** [adonisjs/docs#131]
In chrome 59, the `.overlay` div causes a repaint when scrolling, also it has an invalid `transform` value which looks like it should be `transition` instead. 

```diff
.overlay {
    background: rgba(0,0,0,.4);
    position: fixed;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    opacity: 0;
    pointer-events: none;
-   transform: opacity .2s linear;
+   transition: opacity .2s linear;
+   will-change: transform, opacity;
}
```

Before:
![image](https://user-images.githubusercontent.com/16421948/27514840-d4096b50-59d8-11e7-9e06-c093926ba61e.png)

After:
![image](https://user-images.githubusercontent.com/16421948/27514832-ad27295a-59d8-11e7-9b50-d2f97979fd17.png)  
(75Hz monitor)

**Comment by thetutlage** [comment]
Thanks :)

**Comment by thetutlage** [comment]
Redesigned so should be good
