### ISSUE TITLE
explain connection between Model Relationships and Migrations

### ISSUE THREAD

**Issue by alidcastano** [adonisjs/docs#165]
In the model relationship section, it reads as if when you add a new relationship, the model's operations will continue to automatically. It isn't clear that you need to create the appropriate migrations.

Also, it's important to explain what Lucid relationships do for you so that you can know what migration to create.

For example, for this relationship:

```
owner {
  return this.belongsTo('App/Model/User')
}
```

I'd expect to add the following migration: 

```
table.string('owner').references('id').inTable('users')
```

Whereas from looking at example code, this is what is done: 

```
table.integer('user_id').references('id').inTable('users')
```

I've been using `adonis-rally` to help bring everything together, but I'd be great to see a full explanation or tutorial of how everything works together, especially for something as crucial as relationships/migrations. Thanks!

**Comment by RomainLanz** [comment]
Hey @alidcastano! 👋

You don't need to create an appropriate migration to add a logical relation.
If you take a look at the documentation for migration you'll see:

> **Migrations are mutations to your database** as you keep evolving your application.

and if you look for Lucid's relations you found

> Lucid expressive API makes the process of associating and fetching these relations so straightforward and intuitive, **without even touching the SQL schema**.

I think this is clear of what it is doing.

Concerning your example, AdonisJs use a convention that you can override easily by specifying more parameter. Please take a look at [the documentation](http://dev.adonisjs.com/docs/4.0/relationships#_belongs_to).

Side note: You shouldn't use `string` for relation, these are pretty bad in term of performance.

**Comment by alidcastano** [comment]
Personally, from reading the documentation I thought that the only migrations I had to make are for properties not specified in the Model. But it makes sense that all mutations are recorded separately via migrations since the model doesn't track all the changes to the database over time.

Nonetheless, I still think I'd be great if the documentation linked these concepts. But thanks for the explanation and I'll go ahead and close this issue.

**Comment by alidcastano** [comment]
@RomainLanz Hi, quick question in regards to your comment: if my aim is to use models with short uuids (e.g. `c2c90b39b3fe`), are strings types still not recommended?

**Comment by RomainLanz** [comment]
Use an `uuid` field http://knexjs.org/#Schema-uuid

**Comment by alidcastano** [comment]
Yes but for Postgres that only works for standard, 32 digit uuids

`a0ee-bc99-9c0b-4ef8-bb6d-6bb9-bd38-0a11` versus `2e59ae0513e`
