### ISSUE TITLE
Resource Middleware not working

### ISSUE THREAD

**Issue by liam-potter** [adonisjs/docs#167]
I am attempting to add multiple middleware (`['auth', 'admin']`) to a route resource that looks something like this:

```js
Route.group('api', () => {
  Route
    .resource('parent/child', 'ChildController')
    .apiOnly()
}).prefix('api/v2')
```

The middleware should only apply to `store`, `update` and `delete` methods - the `index` and `show` methods are to be publicly available. In the documentation for Resource Middleware (http://dev.adonisjs.com/docs/4.0/routing#_resource_middleware) it has the following snippet which is meant to solve this problem:

```js
Route
  .resource('users', 'UsersController')
  .middleware(new Map([
    ['auth']: ['users.store', 'users.update', 'users.delete']
  ]))
```

Unfortunately this is not syntactically correct as an `Array` of `Array`s should be comma separated. It also throws an `Unexpected token :` error when trying to run using `adonis serve --dev`. I have tried a variety of ways to get this to work such as the following:

```js
Route
  .resource('parent/child', 'ChildController')
  .apiOnly()
  .middleware(new Map([
    ['auth', 'admin'], ['parent/child.store', 'parent/child.update', 'parent/child.delete'],
  ]))
```

Unfortunately none of the ways I have tried appear to work.

Obviously I can get around this for the time being by simply listing out all my route methods and attaching the middleware to them individually but I would prefer to be able to do it similar to how it is suggested in the documentation.

**Comment by thetutlage** [comment]
Yeah this map thing kind of confuses me too and that's why I documented it wrong. Going to fix it first

So it should be

```
Route
  .resource('users', 'UsersController')
  .middleware(new Map([
      [['users.store', 'users.update', 'users.destroy'], 'auth']
   ]))
```

**Comment by thetutlage** [comment]
@liam-potter Does it work?

**Comment by thetutlage** [comment]
It was docs confusion, personally tried it and it works fine.

**Comment by akusany2** [comment]
Hi, I am having this same issue

```
Route
  .group(() => {
    Route.resource('test', 'TestController')
      .middleware(new Map([
        [['test.store', 'test.update', 'test.delete'], ['auth']]
      ]))
  })
  .prefix('api/v1')
```

The above code gives me this error: `TypeError: Cannot read property 'middleware' of undefined`
