### ISSUE TITLE
Mail.raw() arguments are defined incorrectly

### ISSUE THREAD

**Issue by dusbuss** [adonisjs/docs#171]
In the Mail docs, `Mail.raw` says that it takes three arguments, but it doesn't appear that `raw` takes a data argument. Only a string and a callback.

Thanks!

**Comment by RomainLanz** [comment]
Hey @dusbuss! 👋 

Which version of Adonis are you using?

**Comment by dusbuss** [comment]
Hi. I’m on Adonis 4.0.23, and in the Adonis 4 docks, it says that the `Mail.raw` method accepts three arguments, but the actual code only accepts two arguments: https://github.com/adonisjs/adonis-mail/blob/2674536d59f5c033569f40b558ac394317033e21/src/Mail/Sender.js#L150

**Comment by dusbuss** [comment]
Maybe I'm writing this issue in the wrong repo?

**Comment by thetutlage** [comment]
Yup, need to fix the docs.

**Comment by thetutlage** [comment]
Would you mind opening an issue there? so it will be easier for me to track

**Comment by dusbuss** [comment]
will do
