### ISSUE TITLE
Rename repo to adonis-docs?

### ISSUE THREAD

**Issue by benallfree** [adonisjs/docs#178]
I noticed everything else is prefixed with `adonis-`, which definitely helps when sorting out my forks :)

**Comment by jacekk** [comment]
@benallfree You can seamlessly rename you docs repo to adonis-docs. Fork link will work correctly. Mine works: https://github.com/jacekk/adonisjs-docs :)

**Comment by thetutlage** [comment]
Closing since not actionable
