### ISSUE TITLE
(Validation) Unique rule and Extending Validator doc of v4 is missing

### ISSUE THREAD

**Issue by duyluonglc** [adonisjs/docs#179]
Reference of v3.2 here
http://adonisjs.com/docs/3.2/validator#_unique_tablename_fieldname
http://adonisjs.com/docs/3.2/validator#_extending_validator
Is v4 different with v3?

**Comment by thetutlage** [comment]
It's a documentation bug, mind creating a PR for same?

**Comment by duyluonglc** [comment]
okey man. I'll make a PR
