### ISSUE TITLE
Translation workflow?

### ISSUE THREAD

**Issue by wxs77577** [adonisjs/docs#180]
How to contribute translation?

**Comment by thetutlage** [comment]
Create a new branch with the language name and version, so it will be 

`fr-4.0` for french

**Comment by wxs77577** [comment]
thanks

**Comment by wxs77577** [comment]
I've create a branch `zh-4.0` for chinese translation in my repo, but there is no branch `zh-4.0` in your main repo. Could you add a branch `zh-4.0` ?

**Comment by thetutlage** [comment]
Sure I will do it

**Comment by thetutlage** [comment]
Or I was thinking we can create folders for each language, that way when generating docs, the automated script, will not have to switch branches.

Would you mind nested all of your docs inside `zh` directory?

**Comment by wxs77577** [comment]
@thetutlage ok, I think it's better than use a new branch.
