### ISSUE TITLE
Lint doc code samples?

### ISSUE THREAD

**Issue by benallfree** [adonisjs/docs#181]
Maybe we could adapt this https://github.com/zeke/standard-markdown

**Comment by RomainLanz** [comment]
Hey @benallfree! 👋 

We aren't using Markdown for our documentation.

**Comment by benallfree** [comment]
No I think it could be adapted though. Looking for a way to lint code samples. 

Another idea: move code samples into .js files that can be easily linked, then include the files.

**Comment by thetutlage** [comment]
It can be done but will be a lot of work with small win, since I have lot on my plate right now. I am happy if someone else wants to own this piece and happy to share my thoughts

**Comment by benallfree** [comment]
"this piece" = docs? or linting

**Comment by thetutlage** [comment]
Moving all code blocks to `.js`

**Comment by thetutlage** [comment]
I believe there is nothing much to be done here, we can always open this issue when we have bandwidth to write code around it.
