### ISSUE TITLE
Doc on website is not synced with repo

### ISSUE THREAD

**Issue by outluch** [adonisjs/docs#184]
http://dev.adonisjs.com/docs/4.0/database-basics
`await ('Database').table('blog_posts').insert({ title: 'Adonis 101', body: 'some description' })`
in repo already fixed __`use`__: 
`await use('Database').table('blog_posts').insert({ title: 'Adonis 101', body: 'some description' })`

**Comment by thetutlage** [comment]
Yes, docs are not deployed yet.
