### ISSUE TITLE
Add a specific "Controllers" section to HTTP Lifecycle

### ISSUE THREAD

**Issue by watzon** [adonisjs/docs#190]
It looks like controllers aren't well documented in the v4 API documentation

**Comment by thetutlage** [comment]
@watzon Can u share which part you think is not there. Since I removed the entire topic of controllers from the docs, since there is nothing specific to explain.

But happy to add it back, if you can spot couple of thing

**Comment by watzon** [comment]
I think it makes sense to have a controllers section, even if they don't have any super specific functionality that can't be done with a closure. It would be nice to have a place where it just shows how they're structured, how you can use them to move business logic out of the routes file, etc.

**Comment by thetutlage** [comment]
Something like this? http://dev.adonisjs.com/docs/4.0/routing#_binding_controllers

**Comment by watzon** [comment]
That gives a small example, but it's kinda tucked away and doesn't show an example of request and response being used in a controller. Maybe that section could just be expounded upon though?

**Comment by thetutlage** [comment]
I don't think there is really anything extra happening in Controller, they receive the same argument, but I can update the example to show how to access `request` and `response`.

In short, Controllers are classes with methods and works same as route closures. Literally giving a whole new page to this phrase will be too much.

But I am happy to add if someone can share atleast 3 missing or confusing points.

**Comment by watzon** [comment]
I know that classes and closures in the routes are basically the same thing, but that might not be apparent to people who are new to MVC and the destructuring syntax may not be apparent either. I think just updating the example should be fine though

**Comment by thetutlage** [comment]
Cool! Lemme see if I can also gather some thoughts around what are controller and how they are useful ( from beginners point of view ) and then give it a dedicated doc.

Thanks 😄

**Comment by watzon** [comment]
No problem! I like thinking about how beginners would think about documentation. It makes them much more likely to use this framework, especially since a full framework like this is much easier to get started with than trying to set up an express app with models

**Comment by RomainLanz** [comment]
Handled here https://github.com/adonisjs/docs/pull/298
