### ISSUE TITLE
mobile: dropdown doesnt redirect to needed page

### ISSUE THREAD

**Issue by outluch** [adonisjs/docs#193]
tried in my android + desktop browser with narrow window. No action on choosing topic.

**Comment by RomainLanz** [comment]
Hey @outluch! 👋 

Thanks for your feedback!
I have reproduced the issue with my phone (iOS) and I also get this issue.

The issue appears on the select to change section on the documentation (see the screenshot below).

![img_6449](https://user-images.githubusercontent.com/2793951/32576482-6061d146-c4d7-11e7-843f-ab2ea82ca490.jpg)

**Comment by thetutlage** [comment]
Fixed in https://github.com/adonisjs/adonisjs.com/commit/5d048d303da10304ef09d7df4a3a9b8b09074ac5
