### ISSUE TITLE
wrong namespace on View page in doc

### ISSUE THREAD

**Issue by kei0719** [adonisjs/docs#195]
at [Views ##Basic example](http://adonisjs.com/docs/4.0/views#_basic_example) page has wrong namespace.

**File: docs/04-http-lifecycle/05-views.adoc**

below snippet is

```js
const providers = [
  '@adonisjs/frameworks/providers/ViewProvider'
]
```
should be ...

```js
const providers = [
  '@adonisjs/framework/providers/ViewProvider'
]
```

**Comment by thetutlage** [comment]
Can u please share a PR for same?
