### ISSUE TITLE
Typo in some sections of the docs

### ISSUE THREAD

**Issue by codejockie** [adonisjs/docs#207]
There are various typos in some sections of the docs at [Adonis Docs](https://adonisjs.com/docs/4.0).
I wouldn't mind correcting the typos.

**Comment by thetutlage** [comment]
Happy to accept the PR 😄

**Comment by codejockie** [comment]
I'm guessing this repository will be where I'd be working?

**Comment by codejockie** [comment]
I'd take my time to look through all the sections in the docs so I can fix appropriately.

**Comment by codejockie** [comment]
One more question, are there conventions for commit messages and pull request that I need to know?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
