### ISSUE TITLE
Add docs for switchLocale in view

### ISSUE THREAD

**Issue by ntvsx193** [adonisjs/docs#230]
Issue make from https://forum.adonisjs.com/t/antl-view-with-user-locale/462/6

**Comment by thetutlage** [comment]
I don't think this has to be the part of docs. The `antl` object is shared with view and that means all methods can be called inside view and not only `switchLocale`.

Also I will never never views to mutate state, this is literally the worst way to do something. One should call `antl.switchLocale` inside controller and then render the view.

**Comment by ntvsx193** [comment]
Can you write example code for usage with switchLocale for view in controller?

**Comment by thetutlage** [comment]
```js
controllerMethod ({ antl, view }) {
  antl.switchLocale('fr')
  return view.render('some-view')
}
```

NOTE: The `antl` instance is shared with controller and the view you will render from that controller.

**Comment by ntvsx193** [comment]
Wow! It is great! I think otherwise :)
I am add this to docs

**Comment by thetutlage** [comment]
I will not, since one thing leads to other. If method `a` is documented, then why not `b`, which will end up in duplicated docs everywhere.

**Comment by ntvsx193** [comment]
Okay, i'm found now in docs

http://adonisjs.com/docs/4.0/internationalization#_context_instance
> However, you can also make use of the antl object, which is passed to all route handlers like request and response.

But it's not explicitly indicated.
See new changes from PR
