### ISSUE TITLE
Typo in Authentication

### ISSUE THREAD

**Issue by RaymondLC92** [adonisjs/docs#254]
https://adonisjs.com/docs/4.1/authentication

loginViaId(id)

Should be:

loginVaIid(id)

**Comment by RomainLanz** [comment]
Could you create a PR please?

**Comment by antwaanvh** [comment]
Hi,

I do not think there is a typo here. The docs state the method `loginViaId()`, read `login_via_id`, should:
> Login a user using their id.

**Comment by RaymondLC92** [comment]
I think you're correct.

The font just confused me I suppose.
