### ISSUE TITLE
wrong require in websocket wit cluster section

### ISSUE THREAD

**Issue by Goopil** [adonisjs/docs#260]
Hello guys, first a big thanks for your hard work ! trully a marvellous tool you have build there.

There is a small error in the doc in the ws cluster section
you said to require

`require('@adonisjs/websocket-client/clusterPubSub')()`

but it should be

`require('@adonisjs/websocket/clusterPubSub')()`

Am i wrong ?

**Comment by thetutlage** [comment]
Mind sharing a PR please?
