### ISSUE TITLE
Add a local installation section

### ISSUE THREAD

**Issue by Purexo** [adonisjs/docs#269]
Hello, I propose a new adonis installation section for those who don't want global adonis binary:

prerequisites: npx

```bash
npx @adonisjs/cli new yarnstick
cd yarnstick
npm install -save-dev @adonisjs/cli # possibly to be integrated in the blueprints
npx adonis serve --dev
```

I also suggest adding a `--local` flag to the `new` command of adonis that would add the `npm install --save-dev @adonisjs/cli` command to the installation process
And modify in the end message `adonis serve --dev` by `npx adonis serve --dev`

**Comment by thetutlage** [comment]
I don’t see any benefit in this

**Comment by Purexo** [comment]
Many person didn't like use of global package (sometimes you need different version of same package for some project)

In my experience, it's simplier and recommended to use project dev-dependencies instead global package. Some times you are in an environment where you just can't install global package because you are not admin.

And global package pollute your global binaries and don't need them if your not in a project who use it.

Here is a more complete article of subject. 
https://codeburst.io/maybe-dont-globally-install-that-node-js-package-f1ea20f94a00

**Comment by thetutlage** [comment]
Yes but adonis cli doesn’t stops you from doing what are planning to do.

Why it has to be the part of the official docs?

**Comment by johnpyp** [comment]
I agree with Purexo here. Just because something is not necessarily important to framework specifically doesn't mean it isn't valuable to add it to the docs. There is very little cost to adding sections or subsections to the docs, and I don't think this really bloats the docs up at all.

**Comment by Purexo** [comment]
> Why it has to be the part of the official docs?

Why not. I think it can be more enjoyable for futur Adonis users to avoid manual installation of Adonis binary for starting a project.

If you accept this suggestion, I code it and pr on doc and adonis/cli with supervision of @RomainLanz ;-)

**Comment by thetutlage** [comment]
@Purexo 

How Adonis can be more enjoyable if you install the cli inside your project repo? This seems to be weirdest argument I have ever heard.

Let's take the profile of 2 developers who are reading the docs.

## Beginner
The beginner user will have questions like?

1. Why there are 2 ways to install the cli?
2. Which one is better?
3. Why `adonis serve` etc commands do not work (if he/she installed it locally)

## Advanced

I know the difference between local installation and global installation and can make informed decisions myself.

For both the users, I don't see any point in adding it to the docs.

Also there are many other ways to run binaries in Node.js. One of them is using [builder](https://www.npmjs.com/package/builder). Now should I add docs for this too?

The job of installation doc is to get you up and running and not to teach you the entire Node.js eco-system
