### ISSUE TITLE
Bring back Response methods

### ISSUE THREAD

**Issue by drmzio** [adonisjs/docs#272]
Had to view v3.2 docs to see which response methods were available. More specifically, how to return a response with a 400 status code for when Validation fails. Any reason why these aren't there anymore?

Response methods: https://adonisjs.com/docs/3.2/response#_response_methods

**Comment by antwaanvh** [comment]
Hi @drmzio,

Is this what you're looking for?
```js
response.badRequest()
```

If so, check [this](https://github.com/poppinss/node-res/blob/develop/methods.js) out.

Hope it helps.

**Comment by antwaanvh** [comment]
@drmzio did this help?

**Comment by thetutlage** [comment]
Closing since no response from the issue reporter and not actionable as well
