### ISSUE TITLE
Add an independent scrollbar for the sidebar

### ISSUE THREAD

**Issue by johnpyp** [adonisjs/docs#274]
Similar to the behaviour of https://vuejs.org/v2/guide/ , a side scrollbar independent of the main one would make navigating the docs a lot easier.

**Comment by thetutlage** [comment]
PR welcomed

**Comment by johnpyp** [comment]
I've attempted this here: https://github.com/johnpyp/adonisjs.com/commit/6ad54fbcf454286198273b91bfb771be5638bca9 , though it isn't very polished because I didn't want to change a lot of the structure to make it smooth.
