### ISSUE TITLE
Add Example for Routing with a Public Path

### ISSUE THREAD

**Issue by johnpyp** [adonisjs/docs#275]
Looking for a way to serve my vue dist directory as the wildcard route, I came across this post:
https://forum.adonisjs.com/t/vue-js-spa-within-adonis-js/363/3

I would be nice to have an example like this (as in the post):
`const Helpers = use(‘Helpers’)`
`Route.any('*', ({response}) => response.download(Helpers.publicPath('main.html')))`

This fits for the main ways of creating react and vue front end apps, with create-react-app and vue-cli respectively.

**Comment by thetutlage** [comment]
Create a PR for docs please
