### ISSUE TITLE
Mail.send wrong parameters

### ISSUE THREAD

**Issue by mreschke** [adonisjs/docs#28]
In the docs you have `yield Mail.send('emails/welcome', function (message) {` but when I do that, I get `callback must be a function` error, because it is expecting the callback to be the 3rd paramaters, not the second.

`* send (view, data, callback, config) {`

Not sure what data (view merge fields?).  I just put `yield Mail.send('emails/test', '', function(message) {` as a test and it worked.

**Comment by thetutlage** [comment]
Yes data is used for dynamic values inside views, will fix the docs

**Comment by thetutlage** [comment]
Fixed
