### ISSUE TITLE
Typo in "distributing as a package" section of doc?

### ISSUE THREAD

**Issue by giacomocerquone** [adonisjs/docs#284]
Hi all. I started looking at AdonisJs just yesterday and I think I might have found a typo: https://adonisjs.com/docs/4.1/service-providers#_distributing_as_a_package

In the distributing section there is written

> we will name it as Adonis/Addons/Queue

but then in the code, if I understand the code correctly, you define it as `Bee/Queue`

```

    this.app.singleton('Bee/Queue', () => {
      const Config = this.app.use('Adonis/Src/Config')
      return new (require('../src/Queue'))(Config)
    })
```

If I'm not wrong, please let me issue a pr :)

**Comment by thetutlage** [comment]
Yup, seems like a typo. It should be `Adonis/Addons/Queue` inside the code example. I will be happy to accept a PR for same
