### ISSUE TITLE
There is a bug in WebSockets/ClientAPI

### ISSUE THREAD

**Issue by ekorolev** [adonisjs/docs#342]
https://adonisjs.com/docs/4.1/websocket-client#_offevent_callback

It's a bug. I try to use the method channel.off( listener_function ) and catch an error "eventName must be a string". Then I retry with "channel.off( evenName_string, listener_function )" and it's done.

**Comment by RomainLanz** [comment]
Hey @ekorolev! 👋 

Could you please create a repository with the minimum amount of code to reproduce the issue?

**Comment by ekorolev** [comment]
> Hey @ekorolev! 👋
> 
> Could you please create a repository with the minimum amount of code to reproduce the issue?

No, I haven't any bugs with AdonisJs, instead AdonisJs Documentation has a wrong information. I provided the link (https://adonisjs.com/docs/4.1/websocket-client#_offevent_callback) to the part of documentation which has a wrong info. There are a line number 4 in the code example:

```
const messageHandler = function () {}

chat.on('message', messageHandler)
chat.off(messageHandler)
```

Instead "chat.off(messageHandler)" there should be "chat.off('message', messageHandler)" to be correct.

**Comment by RomainLanz** [comment]
Oops, may you create a PR? 😄

**Comment by ekorolev** [comment]
Yes, sure :)

**Comment by RomainLanz** [comment]
Closing in favor of the PR.
