### ISSUE TITLE
Extending Response example has an error

### ISSUE THREAD

**Issue by begueradj** [adonisjs/docs#353]
Could you please fix the example you provided in the documentation about [Extending Response](https://adonisjs.com/docs/4.1/response#_extending_response) ? 

In my application, I need to extend the Response class. I did it successfully (I get **true** in `console.log(Response.hasMacro('sendStatus'))` ). But I always get a 500 HTTP code error when testing or navigating to that endpoint because the example in the documentation has an issue:

```

const Response = use('Adonis/Src/Response')
Response.macro('sendStatus', function (status) {
  this.status(status).send(status)
})
```
You know that that arrow functions do not have their own bindings to `this`.
We need you please to update that example because that is the only available one that shows how to extend Response or any other AdonisJs class.

[Demo to reproduce](https://github.com/begueradj/error-adonisjs-extend-response-class) the error to which the above example leads.

Thank you very much.
Billal Begueradj

**Comment by RomainLanz** [comment]
Hey @begueradj! 👋 

The example is perfectly fine. Also, it's normal to not use an arrow function since we want `this` to be correctly bound.

**Comment by begueradj** [comment]
Indded, I shared the wrong link, that is why the example above works (different from what I shared in my repo). [Here](https://adonisjs.com/docs/4.1/extending-adonisjs#_adding_macrosgetters) is the concerned typo in the documentation. I sent you a pull request.
Thank you for the help.
