### ISSUE TITLE
Lucid Transactions example typo

### ISSUE THREAD

**Issue by chirgjin** [adonisjs/docs#376]
I recently started using adonis for my project. While checking the documentation at https://adonisjs.com/docs/4.1/lucid#_transactions I noticed that trx.rollback should be a function call and is missing the parenthesis () in the example
![image](https://user-images.githubusercontent.com/5507625/66200105-ef545680-e6bd-11e9-924e-d75b154358a6.png)

Assign it to me & Will create a pull request to fix this

**Comment by thetutlage** [comment]
Indeed :). Thanks for the PR
