### ISSUE TITLE
Getting started tutorial validation fails when posting data

### ISSUE THREAD

**Issue by erkan1991** [adonisjs/docs#38]
Hi,

When following the Getting Started tutorial i have encountered an error. The form inputs were not validating due to incorrect syntax in docs.

The `postData` and `rules` should be the other way round.
<img width="640" alt="screen shot 2016-06-28 at 8 13 51 pm" src="https://cloud.githubusercontent.com/assets/7500305/16412089/c4dab194-3d6d-11e6-9e26-e51d74275865.png">

Correct syntax: 
`const validation = yield Validator.validate(postData, rules)`

http://www.adonisjs.com/docs/3.0/adonis-blog-part5

**Comment by thetutlage** [comment]
Thanks going to fix it

**Comment by thetutlage** [comment]
Done and deployed
