### ISSUE TITLE
http://adonisjs.com/docs/3.0/seeds-and-factories

### ISSUE THREAD

**Issue by rkrishnamoorthy** [adonisjs/docs#41]
Hi,
Just noticed this and saving it for a pull request later. faker.email and everything following should be fake.email() ....

```
const Factory = use('Factory')

Factory.blueprint('App/Model/User', (fake) => {

  return {
    username: fake.username(),
    email: faker.email(),
    password: faker.password(),
    firstName: faker.first(),
    lastName: faker.last()
  }

})
```

**Comment by thetutlage** [comment]
Can u create a PR for same?

**Comment by rkrishnamoorthy** [comment]
In the Seeds-and-factories.md file, it seems to have been already fixed but website seems to show the above error. 
Could you please check ?

From the latest file seeds-and-factories.md

```
const Factory = use('Factory')

Factory.blueprint('App/Model/User', (fake) => {

  return {
    username: fake.username(),
    email: fake.email(),
    password: fake.password(),
    firstName: fake.first(),
    lastName: fake.last()
  }

})
```

**Comment by RomainLanz** [comment]
This has been corrected here https://github.com/adonisjs/docs/commit/dbe18784c806c321ac65b82bcdfcbb623219ae50

The website will be updated soon.

**Comment by rkrishnamoorthy** [comment]
Looks fixed on the site
