### ISSUE TITLE
TypeError: Cannot read property 'assertError' of undefined when running functional test example in the docs

### ISSUE THREAD

**Issue by tafadzwagonera** [adonisjs/docs#417]
I discovered that running the functional test example https://adonisjs.com/docs/4.1/testing#_functional_tests emits a `TypeError` on the `page.session` object which goes away if you include `trait('Test/Session')` I suggest adding `trait('Test/Session')` to the example to bring in the session and resolve the problem with `assertError` method getting called on `undefined`

**Comment by thetutlage** [comment]
Feel free to share a PR for the same 🙂

**Comment by tafadzwagonera** [comment]
Hi Harminder,

Sure thing. I'm on it! Check out https://github.com/adonisjs/docs/pull/419

Regards

**Comment by tafadzwagonera** [comment]
https://github.com/adonisjs/docs/pull/419
