### ISSUE TITLE
Docs for 'Providers'

### ISSUE THREAD

**Issue by andrewdelprete** [adonisjs/docs#47]
I'd love to see how to add custom Providers. Is there any plan to write docs for this?

Thank you!

**Comment by thetutlage** [comment]
I am planning to write a cookbook on how IoC container and Service providers work. Added to the trello board and will complete it soon.

**Comment by thetutlage** [comment]
Docs have been added to 3.1
http://adonisjs.com/docs/3.1/ioc-container
