### ISSUE TITLE
Seeds and factories

### ISSUE THREAD

**Issue by turlup** [adonisjs/docs#48]
Hi,

Thanks for this Node.js MVC Framework. I am very glad I found.

[http://www.adonisjs.com/docs/3.0/seeds-and-factories](http://www.adonisjs.com/docs/3.0/seeds-and-factories)

#each(callback)
```
const users = Factory.model('App/Model/User').create(5)
users.each(function * (user) {
    const post = Factory.model('App/Model/Post').make()
    yield user.posts().save(post);
})
```
=> TypeError: users.each is not a function

When I change by 
```
const users = Factory.model('App/Model/User').create(5)
for (var user of users){
    const post  = Factory.model('App/Model/Post').make()
    yield user.posts().save(post );
}
```
=> TypeError: user.posts is not a function

With post model 
```
'use strict'
const Lucid = use('Lucid')
class User extends Lucid {
  posts() {
    return this.hasMany('App/Model/Post')
  }
}
module.exports = User
```
any ideas ? 

Cheers,

**Comment by thetutlage** [comment]
`create` is an async method, so you need to `yield` it.

```javascript
const users = yield Factory.model('App/Model/User').create(5)
users.each(function * (user) {
  const post = Factory.model('App/Model/Post').make()
  yield user.posts().save(post);
})
```

**Comment by thetutlage** [comment]
Closing the issue. Feel free to create a new issue if you are stuck with anything.

**Comment by turlup** [comment]
lots of thanks; my first step on es2015 ...
