### ISSUE TITLE
Images from relationships.md are not accessible

### ISSUE THREAD

**Issue by mertindervish** [adonisjs/docs#59]
Hi. It seems like your images in `3.0/models/relationships.md` are no longer accessible. Can you reupload them, please. Thanks for the beautiful framework :+1:

![untitled](https://cloud.githubusercontent.com/assets/7361642/18211799/34744f0c-7148-11e6-9ff0-43bc84eb6a62.png)

**Comment by thetutlage** [comment]
Fixed and deployed http://adonisjs.com/docs/3.0/relationships.

Thanks for reporting
