### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by thetutlage** [adonisjs/docs#70]
@navdeepsingh commented on [Wed Oct 05 2016](https://github.com/adonisjs/adonis-framework/issues/301)

![has many through_vux5jm jpg 900x220](https://cloud.githubusercontent.com/assets/2968787/19102531/8af321ea-8aee-11e6-8920-cf34816d54ab.png)

Ref: http://www.adonisjs.com/docs/3.0/relationships

---

@thetutlage commented on [Thu Oct 06 2016](https://github.com/adonisjs/adonis-framework/issues/301#issuecomment-251761884)

Thanks, will fix it 😄

**Comment by Maxximus007** [comment]
Started reading the docs (goood! thanks for that!), found some tiny thingies:
- In Routing: HTTP verbs, there is a small list of supported verbs, but in the route example you use 2 different methods, might confuse ppl.
- In Controllers: UserController and User**s**Controller mixed.

**Comment by ctf0** [comment]
http://adonisjs.com/docs/3.1/routing#_as_name 
```js
Route
  .get('/user/:id', 'UserController.show')
  .as('profile')
```

**Comment by thetutlage** [comment]
Closing since done in corresponding PR
