### ISSUE TITLE
Add redis session driver config docs

### ISSUE THREAD

**Issue by nrempel** [adonisjs/docs#83]
It was not clear to me that the redis config for the redis session driver needs to go in `config.session.redis`. I was putting it in `config.redis` as per the redis docs.

**Comment by nrempel** [comment]
This was difficult to debug because there was no feedback that it was failing. Related issue here: https://github.com/adonisjs/adonis-redis/issues/1

**Comment by thetutlage** [comment]
PR?

**Comment by nrempel** [comment]
Should have time this afternoon!

On Sat, Nov 19, 2016 at 10:45 PM, Harminder Virk <notifications@github.com> wrote:
PR?

**Comment by thetutlage** [comment]
Closing since NO PR has been created.
